from quad_controller_rl.agents.base_agent import BaseAgent
from quad_controller_rl.agents.policy_search import RandomPolicySearch
from quad_controller_rl.agents.Task1_policy import Task1_Policy
from quad_controller_rl.agents.Task2_policy import Task2_Policy
